In [2]:
# Simple iteration
x1 = lambda x2, x3: (5 * x2 + 2 * x3 + 2) / 2
x2 = lambda x1, x3: -2 + 4*x3 - x1
x3 = lambda x1, x2: (1 - 3*x2 + 0.5*x1) / 2
e = 10**-4

In [3]:
import numpy as np


def simple_iteration(x0):
    k = 0
    x = np.array([x1(x0[1], x0[2]),
                  x2(x0[0], x0[2]),
                  x3(x0[0], x0[1])])
    while any(abs(x0[i] - x[i]) >= e for i in range(3)):
        print(x)
        x0 = x
        x = np.array([x1(x0[1], x0[2]),
                  x2(x0[0], x0[2]),
                  x3(x0[0], x0[1])])
        k += 1

    return k, x


In [4]:
print(simple_iteration([2, -2, 1]))

[-3.  0.  4.]
[ 5.   17.   -0.25]
[ 43.25  -8.   -23.75]
[ -42.75   -140.25     23.3125]
[-326.3125  134.      200.1875]
[ 536.1875   1125.0625   -282.078125]
[ 2531.578125 -1666.5      -1553.046875]
[-5718.296875   -8745.765625    3133.14453125]
[-18730.26953125  18248.875       11689.57421875]
[ 57312.76171875  65486.56640625 -32055.37988281]
[ 131662.03613281 -185536.28125     -83901.15917969]
[-547740.86230469 -467268.67285156  311220.4309082 ]
[-856950.2512207  1792620.5859375   563968.29370117]
[ 5045520.75854492  3112821.42602539 -2903167.94171143]
[  4878886.62335205 -16658194.52539062  -3407851.44940186]
[-45053336.76287842 -18510294.42095947  26207013.94392395]
[-2.00687211e+07  1.49881391e+08  1.65021079e+07]
[ 3.91205585e+08  8.60771509e+07 -2.29839266e+08]
[-1.46463874e+07 -1.31056265e+09 -3.13143295e+07]
[-3.30772095e+09 -1.10610933e+08  1.96218238e+09]
[ 1.68565505e+09  1.11564505e+10 -6.61013839e+08]
[ 2.72301123e+10 -4.32971041e+09 -1.63132619e+10]
[-2.71375379e+10 -9.

C:\Users\Самыел\AppData\Local\Temp\ipykernel_1912\2059345900.py:2: RuntimeWarning: overflow encountered in scalar add
  x1 = lambda x2, x3: (5 * x2 + 2 * x3 + 2) / 2
C:\Users\Самыел\AppData\Local\Temp\ipykernel_1912\2059345900.py:3: RuntimeWarning: overflow encountered in scalar subtract
  x2 = lambda x1, x3: -2 + 4*x3 - x1
C:\Users\Самыел\AppData\Local\Temp\ipykernel_1912\2059345900.py:3: RuntimeWarning: overflow encountered in scalar multiply
  x2 = lambda x1, x3: -2 + 4*x3 - x1
C:\Users\Самыел\AppData\Local\Temp\ipykernel_1912\2059345900.py:4: RuntimeWarning: invalid value encountered in scalar add
  x3 = lambda x1, x2: (1 - 3*x2 + 0.5*x1) / 2
C:\Users\Самыел\AppData\Local\Temp\ipykernel_1912\2926966368.py:9: RuntimeWarning: invalid value encountered in scalar subtract
  while any(abs(x0[i] - x[i]) >= e for i in range(3)):


In [5]:
def jacobi(A, b, tolerance=1e-3, max_iterations=100):
    
    x = np.zeros_like(b, dtype=np.double)
    
    T = A - np.diag(np.diagonal(A))
    
    for _ in range(max_iterations):
        
        x_old  = x.copy()
        
        x[:] = (b - np.dot(T, x)) / np.diagonal(A)
        
        if np.linalg.norm(x - x_old, ord=np.inf) / np.linalg.norm(x, ord=np.inf) < tolerance:
            break
            
    return x

In [6]:
A = np.array([[2, -5, -2],
             [1, 1, -4],
             [-0.5, 3, 2]])
b = np.array([2, -2, 1])
print(jacobi(A, b))

[-8.35231082e+44 -1.69146879e+46 -2.01632692e+43]


In [7]:
g = lambda x3: 1 + x3
f = lambda x1: (1 + 0.5*x1) / 2

In [8]:
def simple_iteration(x0, y0):

    x = g(x0)
    y = f(y0)
    k = 1

    while abs(x - x0) > e or abs(y - y0) > e:

        x0 = x
        y0 = y

        x = g(y0)
        y = f(x0)

        k += 1

    return k, x, 0, y


In [9]:
print(simple_iteration(2, 0))

(16, 1.999969482421875, 0, 1.0000152587890625)


![Simple iteration](img/Simple_iteration_for_slau.png)

![Convergance](img/Simple_iter_convergence.png)

In [10]:
import numpy as np

A = np.array([
    [2, -5, -2],
    [1, 1, -4],
    [-0.5, 3, 2]
    ], dtype=float)

def shod(A):
    tau = 1 / np.max(np.abs(np.diag(A)))  # Оптимальный параметр tau
    B = np.eye(len(A)) - tau * A

    # Вычисляем спектральный радиус
    rho = max(abs(np.linalg.eigvals(B)))

    print("Спектральный радиус B:", rho)
    print("Сходимость метода:", rho < 1)

shod(A)


Спектральный радиус B: 1.996514683283354
Сходимость метода: False


In [11]:
C = np.array([
    [2, -2],
    [-0.5, 2]
    ])

shod(C)

Спектральный радиус B: 0.5000000000000001
Сходимость метода: True
